apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# The metadata section is for specifying essential details about your EKS cluster.
metadata:
  # name: The name of your EKS cluster.
  name: fargate-quickstart
  # region: The AWS region where your EKS cluster will be created.
  region: us-east-1
  # version: The Kubernetes version to use for your EKS cluster.
  version: "1.29"

# The fargateProfiles section is for configuring Fargate profiles, which determine which pods run on Fargate when launched into specified namespaces.
fargateProfiles:
  - name: fp-default  # Name of the Fargate profile.
    selectors:
      # namespaces: List of namespaces where pods should be run on Fargate. These can be either predefined namespaces or custom ones you create. Up to five namespaces can be specified.
      - namespace: default
      - namespace: kube-system
      - namespace: my-cool-app
      - namespace: cert-manager
      - namespace: opentelemetry-operator-system

# The IAM section is for managing IAM roles and service accounts for your cluster.
iam:
  # withOIDC: Enable the creation of the OIDC provider associated with the cluster to allow for IAM Roles for Service Accounts (IRSA).
  withOIDC: true
  serviceAccounts:
  - metadata:
      # Service account used by the AWS Load Balancer Controller.
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: adot-collector
      # this is to create the namespace my-cool-app
      namespace: my-cool-app
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"

# The cloudWatch section is for configuring logging for your cluster.
cloudWatch:
  clusterLogging:
    # enableTypes: Which types of logs to enable. '*' represents all types.
    enableTypes: ["*"]
    # logRetentionInDays: The number of days to retain log events.
    logRetentionInDays: 30
